CONFIG: Add pathing checks -- should work now

diff --git a/git-hooks/commit-msg b/git-hooks/commit-msg
--- a/git-hooks/commit-msg
+++ b/git-hooks/commit-msg
@@ -1,7 +1,8 @@
 #!/bin/bash
 
 if [ -z "$ISL" ]; then
-   echo "Need to set ISL env var to use commit-msg checker"
+   echo "Error: need to set ISL env var to repo root to use commit-msg checker"
+   exit 1
 fi
 
 source "$ISL/git-hooks/commit-msg-checker.sh"
