DOCS: Again

diff --git a/.github/workflows/sandbox_pytest.yaml b/.github/workflows/sandbox_pytest.yaml
--- a/.github/workflows/sandbox_pytest.yaml
+++ b/.github/workflows/sandbox_pytest.yaml
@@ -32,104 +32,54 @@ jobs:
             git fetch --depth 1 origin ${{ github.sha }} || { echo "FAIL: Could not fetch from remote."; exit 3; }
             git checkout ${{ github.sha }} || { echo "FAIL: Could not checkout commit."; exit 3; }
 
-  setup_sandbox:
-    runs-on: ubuntu-latest
-    needs: setup_dummy_repo
-    timeout-minutes: 10
-    env:
-      REMOTE_USER: ${{ secrets.REMOTE_USER }}
-      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
-    steps:
-      - name: Create sandbox conda environment and pip install requirements
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.REMOTE_HOST }}
-          username: ${{ secrets.REMOTE_USER }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
-          script: |
-            cd ~/.sandbox/IslandOfMisfitToys || { echo "FAIL: Could not change to IslandOfMisfitToys."; exit 2; }
-            cd .github/workflows/scripts || { echo "FAIL: Could not change to scripts directory."; exit 2; }
-            ./setup_sandbox.sh ${{ github.sha }}
-            exit_code=$?
-            if [ $exit_code -ne 0 ]; then
-              echo "FAIL: Could not setup sandbox. exit_code=$exit_code"
-              exit $exit_code
-            fi
+  # setup_sandbox:
+  #   runs-on: ubuntu-latest
+  #   needs: setup_dummy_repo
+  #   timeout-minutes: 10
+  #   env:
+  #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
+  #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
+  #   steps:
+  #     - name: Create sandbox conda environment and pip install requirements
+  #       uses: appleboy/ssh-action@master
+  #       with:
+  #         host: ${{ secrets.REMOTE_HOST }}
+  #         username: ${{ secrets.REMOTE_USER }}
+  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
+  #         script: |
+  #           cd ~/.sandbox/IslandOfMisfitToys || { echo "FAIL: Could not change to IslandOfMisfitToys."; exit 2; }
+  #           cd .github/workflows/scripts || { echo "FAIL: Could not change to scripts directory."; exit 2; }
+  #           ./setup_sandbox.sh ${{ github.sha }}
+  #           exit_code=$?
+  #           if [ $exit_code -ne 0 ]; then
+  #             echo "FAIL: Could not setup sandbox. exit_code=$exit_code"
+  #             exit $exit_code
+  #           fi
 
-  run_pytest:
-    runs-on: ubuntu-latest
-    needs: setup_sandbox
-    timeout-minutes: 20
-    steps:
-      - name: Run pytest and capture results to a temporary file
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.REMOTE_HOST }}
-          username: ${{ secrets.REMOTE_USER }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
-          script: |
-            cd ~/.sandbox/IslandOfMisfitToys
-            conda activate dw_sandbox
-            cd .github/workflows/scripts/pytest
-            ./validate_gpu.sh ${{ github.sha }} 2>&1 | tee tmp.txt
-            exit_code=${PIPESTATUS[0]}
-            echo "Exit Code: $exit_code"
-            echo "::set-output name=exit_code::$exit_code"
-            PYTEST_RESULTS=$(cat tmp.txt | tail -1)
-            # ensure pytest actually finished with a summary by
-            #     checking for =====...===== at the beginning of the line
-            if [[ $PYTEST_RESULTS =~ ^=+ ]]; then
-              PYTEST_RESULTS="NO_SUMMARY_FOUND"
-            fi
-            rm -rf ~/.sandbox/IslandOfMisfitToys && echo "Deleted sandbox successfully"
-            exit $exit_code
-
-  build_docs:
-    runs-on: ubuntu-latest
-    needs: run_pytest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
-
-      - name: Set up Python
-        uses: actions/setup-python@v2
-        with:
-          python-version: "3.x"
-
-      - name: Install documentation dependencies
-        run: |
-          python -m venv venv
-          source venv/bin/activate
-          pip install -r docs_requirements.txt
-
-      - name: Build documentation
-        run: |
-          source venv/bin/activate
-          cd docs
-          make html
-
-      - name: Upload documentation artifacts
-        uses: actions/upload-artifact@v2
-        with:
-          name: docs
-          path: docs/build/html
-
-  deploy_docs:
-    runs-on: ubuntu-latest
-    needs: build_docs
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
-
-      - name: Download documentation artifacts
-        uses: actions/download-artifact@v2
-        with:
-          name: docs
-          path: docs/build/html
-
-      - name: Deploy to GitHub Pages
-        uses: peaceiris/actions-gh-pages@v3
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: docs/build/html
-          publish_branch: gh-pages
+  # run_pytest:
+  #   runs-on: ubuntu-latest
+  #   needs: setup_sandbox
+  #   timeout-minutes: 20
+  #   steps:
+  #     - name: Run pytest and capture results to a temporary file
+  #       uses: appleboy/ssh-action@master
+  #       with:
+  #         host: ${{ secrets.REMOTE_HOST }}
+  #         username: ${{ secrets.REMOTE_USER }}
+  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
+  #         script: |
+  #           cd ~/.sandbox/IslandOfMisfitToys
+  #           conda activate dw_sandbox
+  #           cd .github/workflows/scripts/pytest
+  #           ./validate_gpu.sh ${{ github.sha }} 2>&1 | tee tmp.txt
+  #           exit_code=${PIPESTATUS[0]}
+  #           echo "Exit Code: $exit_code"
+  #           echo "::set-output name=exit_code::$exit_code"
+  #           PYTEST_RESULTS=$(cat tmp.txt | tail -1)
+  #           # ensure pytest actually finished with a summary by
+  #           #     checking for =====...===== at the beginning of the line
+  #           if [[ $PYTEST_RESULTS =~ ^=+ ]]; then
+  #             PYTEST_RESULTS="NO_SUMMARY_FOUND"
+  #           fi
+  #           rm -rf ~/.sandbox/IslandOfMisfitToys && echo "Deleted sandbox successfully"
+  #           exit $exit_code
